version: '3.5'
#docker-compose up -d --build to build and run see here for more info https://mherman.org/blog/2017/12/07/dockerizing-a-react-app/
services:

  sample-app:
    container_name: sample-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
